config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#index"
  resources :events, only: [:index, :show] do
    resources :guests, only: [:create]
  end
  namespace :administrator do
    resources :events, only: [:new, :create, :show]  do
      resources :guests, only: [:create]
    end
    resources :photos, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  mount_uploader :photo, PictureUploader

  belongs_to :user
  has_many :guests

  validates :title, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}

end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :user
  belongs_to :event

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events
  has_many :photos
  has_many :guests
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/administrator/events_controller.rb
class Administrator::EventsController < ApplicationController
  before_action :authenticate_user!

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.create(event_params)
    if @event.valid?
      redirect_to administrator_event_path(@event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @event = Event.find(params[:id])
    @guest = Guest.new
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :cost, :photo)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @guest = Guest.new
  end
end

app/controllers/guest_controller.rb
class GuestController < ApplicationController
  before_action :authenticate_user!

  def create
    @event = Event.find(params[:event_id])
    @event.guests.create(guest_params.merge(user: current_user))
    redirect_to event_path(@event)
  end  
  
  private

  def guest_params
    params.require(:guest).permit(:first_name, :last_name, :number_of_guest)
  end  
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :authenticate_user!

  def create
    @event = Event.find(params[:event_id])
    @event.guests.create(guest_params.merge(user: current_user))
    redirect_to event_path(@event)
  end  
  
  private

  def guest_params
    params.require(:guest).permit(:first_name, :last_name, :number_of_guest)
  end  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    
  end 
end

app/helpers/administrator/events_helper.rb
module Administrator::EventsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/guest_helper.rb
module GuestHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/administrator/events/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new event</h1>

  <%= simple_form_for @event, url: administrator_events_path do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :cost %>
    <%= f.input :photo %>
    <br />
    <%= f.submit "Create", class: 'btn btn-primary' %>
    <br />
  <% end %>
  <br />

</div>

app/views/administrator/events/show.html.erb

<br />
<div class="booyah-box col-10 offset-1">
  <h1 class="text-center"><%= @event.title %></h1>
  <% unless @event.photo.url.nil? %>
    <%= image_tag @event.photo.url, class: 'img-fluid' %>
  <% end %>
</div>
<div class="clr"></div>
<div class="centro text-center">
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Click Here to Join this Event
</button>
</div>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Register Now</h4>
      </div>
      <%= simple_form_for @guest, url: event_guests_path(@event) do |f| %>
        <div class="modal-body">
          <%= f.input :first_name %>
          <%= f.input :last_name %>
          <%= f.input :number_of_guest %>       
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Register Now", class: 'btn btn-primary' %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>
<div class="row feature text-center">
  <div class="col-12 col-sm">
    <h1>Support This Good Cause</h1>
  </div>
</div>

app/views/events/index.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1 class="text-center">Participate and donate in an event today</h1>
  <hr />

  <% @events.each do |event| %>
    <h2 class="text-center">
      <%= link_to event.title, event_path(event) %>
    </h2>
      <% unless event.photo.url.nil? %>
        <%= image_tag event.photo.url, class: 'img-fluid' %>
      <% end %>
    <br />
    <div class="row">
      <div class="col-sm-8 col-12">
        <%= event.description %>
      </div>
      <div class="col-sm-4 col-12 text-center">
        <%= link_to 'More Details...', event_path(event), class: 'btn btn-primary btn-large' %>
      </div>
    </div>
    <br class="clr" />
  <% end %>

</div>

app/views/events/show.html.erb

<br />

<div class="booyah-box col-10 offset-1">
  <h1><%= @event.title %></h1>
  <% unless @event.photo.url.nil? %>
    <%= image_tag @event.photo.url, class: 'img-fluid' %>
  <% end %>
  <br />
  <div class="row">
    <div class="col-sm-4 col-12" text-center>
      <span class="badge badge-default">
        <%= number_to_currency @event.cost %>
        <%= ' per guest' %>
      </span>   

      <% if current_user && current_user == @event.user %>
        <br />
        <br />
        <%= link_to 'Manage', administrator_event_path(@event), class: 'btn btn-danger btn-large' %>
      <% end %>

    </div>

    <div class="col-sm-8 col-12">
      <%= @event.description %>
    </div>
  </div>
</div>
<div class="clr"></div>
<div class="centro text-center"> 
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal" %>
  Click Here to Join this Event
</button>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Register NOW</h4>
      </div>
      <%= simple_form_for @guest, url: event_guests_path(@event) do |f| %>
        <div class="modal-body">
          <%= f.input :first_name %>
          <%= f.input :last_name %>
          <%= f.input :number_of_guest %>       
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> 
          <%= f.submit "Register Now", class: 'btn btn-primary' %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>
<div class="row feature text-center">
  <div class="col-12 col-sm">
    <h1>Support This Good Cause</h1>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fundraiser</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="flex-content-container">
      <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%= link_to 'Fundraiser', root_url, class: 'navbar-brand' %>
        
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-md-0">
            <li class="nav-item">
              <%= link_to 'See All Events', events_path, class: 'nav-link' %>
            </li>
          </ul>

          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>

        </div>
      </nav>

      <% if notice.present? %>
        <p class="alert alert-info"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>

    <div id="footer">
      <div class="container">
        <b>Administrator</b>
        <br />
        <%= link_to 'Set up Event', new_administrator_event_path %>
      </div>
    </div>      
  </body>
</html>

app/views/static_pages/index.html.erb
<div class="hero">
  <br />
   <div class="frosty col-10 offset-1 text-center">
    <br />
    <h1>Support Our Community Youth Group</h1>
    <br />
    <%= link_to 'Learn More', events_path, class: 'btn btn-success' %>
    <br /><br />
  </div>
</div>
<br />
<div class="row feature text-center">
  <div class="col-12 col-sm">
    <h3>Participate in the Different Events</h3>
    <br />
  </div>

  <div class="col-12 col-sm">
    <h3>Get involve in the Various Programs</h3>
  </div>

  <div class="col-12 col-sm">
    <h3>Join our Community</h3>
  </div>
</div>